# Core definitions
.core-defs:
  variables:
    CORENAME: holani

include:
  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/rust-linux-aarch64.yml' 

stages:
  - build-prepare
  - build-shared 
  - build-static

# Linux 64-bit
libretro-build-linux-aarch64:
  extends:
    - .libretro-rust-linux-aarch64-default
    - .core-defs
