name: Deploy Workflow
on:
  push:
    tags:
      - "*"
jobs:
  build-linux:
    name: Build Linux
    timeout-minutes: 30
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Check architecture
        run: |
          uname -a
          find $(rustc --print sysroot) -name 'libstd-*.rlib' | sed -ne 's:^.*/\([^/]*\)/lib/libstd-[^/]*.rlib:\1:p'
      - name: Checkout code from repository
        uses: actions/checkout@v4
      - name: Build Base
        run: cargo build --release  
      - name: Transform filenames
        run: mv target/release/libholani.so holani_libretro-aarch64-linux.so
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: holani-aarch64-linux
          path: holani_libretro-aarch64-linux.so
          retention-days: 5
          
  release:
    name: Release
    needs: [build-linux]
    timeout-minutes: 10
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag: Linux_aarch64
          files: |
            holani-aarch64-linux/holani_libretro-aarch64-linux.so
