name: holani libretro Linux aarch64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Linux:
    name: Build for Linux
    runs-on: ubuntu-19.10-arm

    steps:
    - name: Install needed packages
      run: sudo apt update && sudo apt install wget git build-essential make
    - name: Checkout source
      run: git clone https://github.com/LLeny/holani-retro.git && cd holani-retro && git submodule update --init --recursive
    - name: Build libretro core
      working-directory: holani-retro
      run: |
        mkdir build && cd build && cmake .. -DLIBRETRO=ON -DUSE_GLES2=ON -DUSE_EGL=ON
        make -j8
        wget https://raw.githubusercontent.com/libretro/libretro-super/master/retrolink.sh && chmod +x retrolink.sh && ./retrolink.sh holani_pod_libretro.so
    - name: Create new release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: Linux_aarch64
        file: holani_pod_libretro.so
        overwrite: true
